version: '3.8'
services:
  eureka-server:
    build: /eureka-server
    image: eureka_image
    container_name: eureka_container
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_PORT=8761
      - EUREKA_SERVER_INSTANCE_HOST=localhost
      - EUREKA_SERVER_CLIENT_DEFAULT_ZONE=http://localhost:8761/eureka/