userinfo:
  base-uri: lb://storage-of-company-information
server:
  port: 8082
spring:
  application:
    name: find-by-company-information
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/