server:
  port: ${EUREKA_SERVER_PORT}
eureka:
  instance:
    hostname: ${EUREKA_SERVER_INSTANCE_HOST}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_CLIENT_DEFAULT_ZONE}